version: '3.8'

services:
  api:
    build: 
      context: .
      args:
        - BASE_IMAGE=${BASE_IMAGE:-python:3.9-slim-buster}
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: app
    ports:
      - "8000:8000"
