version: '3.9'

services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
